CREATE TABLE "CARS" (
    "ID" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "LICENCE_PLATE"  VARCHAR(8)     NOT NULL,
  "MODEL"          VARCHAR(32)    NOT NULL,
  "RENTAL_PAYMENT" DECIMAL(10, 1) NOT NULL,
  "STATUS"         BOOLEAN        NOT NULL
);

CREATE TABLE "CUSTOMERS" (
    "ID" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "FULL_NAME"    VARCHAR(60)  NOT NULL,
  "ADDRESS"      VARCHAR(100) NOT NULL,
  "PHONE_NUMBER" VARCHAR(32)  NOT NULL
);

CREATE TABLE "LEASES" (
    "ID" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "CUSTOMER" INTEGER NOT NULL REFERENCES CUSTOMERS(ID),
    "CAR" INTEGER NOT NULL REFERENCES CARS(ID),
  "PRICE"      DECIMAL(10, 1) NOT NULL,
  "START_DATE" DATE           NOT NULL,
  "END_DATE"   DATE           NOT NULL
);